"""OpenAPI / Typed Client MVP：本地 HTTP 契约只读清单。"""

from __future__ import annotations

from collections import Counter
from typing import Any

VERSION = "openapi-typed-client-mvp"

GROUP_LABELS = {
    "stories": "故事与项目",
    "runs": "运行与分支",
    "jobs": "异步任务",
    "settings": "设置与边界",
    "exports": "导出与评审",
}


def get_api_contract() -> dict[str, Any]:
    """Return a read-only local API contract without scanning secrets or writing files."""

    endpoints = _endpoints()
    groups = _groups(endpoints)
    openapi = _openapi(endpoints)
    client_methods = [
        {
            "client_method": endpoint["client_method"],
            "method": endpoint["method"],
            "path": endpoint["path"],
            "operation_id": endpoint["operation_id"],
            "response_type": endpoint["response_type"],
            "group": endpoint["group"],
        }
        for endpoint in endpoints
        if endpoint.get("client_method")
    ]
    return {
        "version": VERSION,
        "mode": "read_only_api_contract",
        "status": "ready",
        "summary": {
            "endpoint_count": len(endpoints),
            "openapi_path_count": len(openapi["paths"]),
            "typed_client_method_count": len(client_methods),
            "writes_artifacts": False,
            "external_services_required": False,
            "plaintext_key_returned": False,
            "generated_client_written": False,
        },
        "openapi": openapi,
        "groups": groups,
        "endpoints": endpoints,
        "typed_client": {
            "status": "manual_mapping_ready",
            "client_source": "engine/ui/src/api/client.ts",
            "types_source": "engine/ui/src/api/types.ts",
            "methods": client_methods,
            "generation": {
                "mode": "read_only_manifest",
                "writes_files": False,
                "generated_client_exists": False,
                "recommendation": "先固定本地契约清单；需要桌面壳或外部前端时再做生成型 client。",
            },
        },
        "boundaries": [
            "只读返回本地 HTTP 契约和前端类型映射。",
            "不生成文件，不写 artifact，不改变现有手写 client 行为。",
            "不读取、不返回也不记录明文密钥。",
            "不接外部 API 网关、插件市场或云端 schema registry。",
        ],
        "next_steps": [
            "用该清单对齐桌面壳、外部前端或插件接入前的端点范围。",
            "后续如需生成型 client，先基于本清单补齐 schema 细节，再 opt-in 写入生成产物。",
        ],
    }


def _groups(endpoints: list[dict[str, Any]]) -> list[dict[str, Any]]:
    counts = Counter(endpoint["group"] for endpoint in endpoints)
    return [
        {
            "id": group_id,
            "label": GROUP_LABELS[group_id],
            "endpoint_count": counts[group_id],
        }
        for group_id in GROUP_LABELS
        if counts[group_id]
    ]


def _openapi(endpoints: list[dict[str, Any]]) -> dict[str, Any]:
    schemas = {
        endpoint["response_type"]: {"type": "object", "additionalProperties": True}
        for endpoint in endpoints
        if endpoint.get("response_type")
    }
    paths: dict[str, Any] = {}
    for endpoint in endpoints:
        status_codes = endpoint.get("status_codes") or [200]
        paths.setdefault(endpoint["path"], {})[endpoint["method"].lower()] = {
            "operationId": endpoint["operation_id"],
            "summary": endpoint["summary"],
            "tags": [GROUP_LABELS[endpoint["group"]]],
            "responses": {
                str(code): _response_spec(code, endpoint["response_type"])
                for code in status_codes
            },
        }
    return {
        "openapi": "3.1.0",
        "info": {
            "title": "未终章本地 API 契约",
            "version": VERSION,
            "description": "本地只读契约清单，用于前端类型、桌面壳和外部集成准备。",
        },
        "paths": paths,
        "components": {"schemas": schemas},
    }


def _response_spec(code: int, response_type: str) -> dict[str, Any]:
    if code == 200:
        return {
            "description": "成功",
            "content": {
                "application/json": {
                    "schema": {"$ref": f"#/components/schemas/{response_type}"}
                }
            },
        }
    return {"description": _status_description(code)}


def _status_description(code: int) -> str:
    return {
        400: "参数或标识非法",
        404: "资源不存在",
        409: "状态冲突或不可操作",
    }.get(code, "错误")


def _endpoint(
    group: str,
    method: str,
    path: str,
    summary: str,
    operation_id: str,
    response_type: str,
    *,
    client_method: str | None = None,
    status_codes: list[int] | None = None,
) -> dict[str, Any]:
    return {
        "group": group,
        "method": method,
        "path": path,
        "summary": summary,
        "operation_id": operation_id,
        "response_type": response_type,
        "client_method": client_method,
        "status_codes": status_codes or [200, 400, 404],
    }


def _endpoints() -> list[dict[str, Any]]:
    return [
        _endpoint(
            "stories",
            "GET",
            "/api/stories",
            "读取故事列表",
            "listStories",
            "StoryListResponse",
            client_method="listStories",
            status_codes=[200],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/anchor",
            "读取世界锚定",
            "getWorldAnchor",
            "WorldAnchor",
            client_method="getWorldAnchor",
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/project-workspace",
            "读取长篇项目工作台",
            "getProjectWorkspace",
            "ProjectWorkspace",
            client_method="getProjectWorkspace",
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/runtime-preflight",
            "读取运行前体检",
            "getRuntimePreflight",
            "RuntimePreflightReport",
            client_method="getRuntimePreflight",
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/vector-retrieval-readiness",
            "读取向量检索就绪探针",
            "getVectorRetrievalReadiness",
            "VectorRetrievalReadinessReport",
            client_method="getVectorRetrievalReadiness",
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/embedding-evaluation-samples",
            "读取 embedding 评测样本",
            "getEmbeddingEvaluationSamples",
            "EmbeddingEvaluationSamplesReport",
            client_method="getEmbeddingEvaluationSamples",
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-trigger-evidence",
            "读取 GraphRAG/Zep 触发证据",
            "getGraphMemoryTriggerEvidence",
            "GraphMemoryTriggerEvidenceReport",
            client_method="getGraphMemoryTriggerEvidence",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-spike-design-pack",
            "读取 GraphRAG/Zep spike 设计包",
            "getGraphMemorySpikeDesignPack",
            "GraphMemorySpikeDesignPackReport",
            client_method="getGraphMemorySpikeDesignPack",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-shadow-compare-pack",
            "读取 GraphRAG/Zep shadow 对照包",
            "getGraphMemoryShadowComparePack",
            "GraphMemoryShadowComparePackReport",
            client_method="getGraphMemoryShadowComparePack",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-shadow-case-matrix",
            "读取 Graph 记忆 shadow case 矩阵",
            "getGraphMemoryShadowCaseMatrix",
            "GraphMemoryShadowCaseMatrixReport",
            client_method="getGraphMemoryShadowCaseMatrix",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-boundary-matrix",
            "读取 Graph 记忆 provider 边界矩阵",
            "getGraphMemoryProviderBoundaryMatrix",
            "GraphMemoryProviderBoundaryMatrixReport",
            client_method="getGraphMemoryProviderBoundaryMatrix",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-offline-shadow-replay-plan",
            "读取 Graph 记忆离线 shadow replay 计划",
            "getGraphMemoryOfflineShadowReplayPlan",
            "GraphMemoryOfflineShadowReplayPlanReport",
            client_method="getGraphMemoryOfflineShadowReplayPlan",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-offline-shadow-replay-report",
            "读取 Graph 记忆离线 shadow replay 结果报告",
            "getGraphMemoryOfflineShadowReplayReport",
            "GraphMemoryOfflineShadowReplayReport",
            client_method="getGraphMemoryOfflineShadowReplayReport",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-fixture-pack",
            "读取 Graph 记忆 provider spike fixture pack",
            "getGraphMemoryProviderSpikeFixturePack",
            "GraphMemoryProviderSpikeFixturePackReport",
            client_method="getGraphMemoryProviderSpikeFixturePack",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-readiness-gate",
            "读取 Graph 记忆 provider spike readiness gate",
            "getGraphMemoryProviderSpikeReadinessGate",
            "GraphMemoryProviderSpikeReadinessGateReport",
            client_method="getGraphMemoryProviderSpikeReadinessGate",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-runbook",
            "读取 Graph 记忆 provider spike 人工 dry-run SOP",
            "getGraphMemoryProviderSpikeRunbook",
            "GraphMemoryProviderSpikeRunbookReport",
            client_method="getGraphMemoryProviderSpikeRunbook",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-dry-run-result-template",
            "读取 Graph 记忆 provider spike 人工 dry-run 结果记录模板",
            "getGraphMemoryProviderSpikeDryRunResultTemplate",
            "GraphMemoryProviderSpikeDryRunResultTemplateReport",
            client_method="getGraphMemoryProviderSpikeDryRunResultTemplate",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-mock-result-report",
            "读取 Graph 记忆 provider spike mock 结果报告",
            "getGraphMemoryProviderSpikeMockResultReport",
            "GraphMemoryProviderSpikeMockResultReport",
            client_method="getGraphMemoryProviderSpikeMockResultReport",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-review-gate",
            "读取 Graph 记忆 provider spike 人工复核 gate",
            "getGraphMemoryProviderSpikeReviewGate",
            "GraphMemoryProviderSpikeReviewGateReport",
            client_method="getGraphMemoryProviderSpikeReviewGate",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-manual-approval-pack",
            "读取 Graph 记忆 provider spike 人工审批包",
            "getGraphMemoryProviderSpikeManualApprovalPack",
            "GraphMemoryProviderSpikeManualApprovalPackReport",
            client_method="getGraphMemoryProviderSpikeManualApprovalPack",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-manual-approval-evidence-checklist",
            "读取 Graph 记忆 provider spike 审批证据核对表",
            "getGraphMemoryProviderSpikeManualApprovalEvidenceChecklist",
            "GraphMemoryProviderSpikeManualApprovalEvidenceChecklistReport",
            client_method="getGraphMemoryProviderSpikeManualApprovalEvidenceChecklist",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-opt-in-evidence-snapshot",
            "读取 Graph 记忆 provider spike opt-in 证据快照",
            "getGraphMemoryProviderSpikeOptInEvidenceSnapshot",
            "GraphMemoryProviderSpikeOptInEvidenceSnapshotReport",
            client_method="getGraphMemoryProviderSpikeOptInEvidenceSnapshot",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-opt-in-no-go-matrix",
            "读取 Graph 记忆 provider spike opt-in no-go 矩阵",
            "getGraphMemoryProviderSpikeOptInNoGoMatrix",
            "GraphMemoryProviderSpikeOptInNoGoMatrixReport",
            client_method="getGraphMemoryProviderSpikeOptInNoGoMatrix",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-opt-in-operator-checklist",
            "读取 Graph 记忆 provider spike opt-in 人工操作清单",
            "getGraphMemoryProviderSpikeOptInOperatorChecklist",
            "GraphMemoryProviderSpikeOptInOperatorChecklistReport",
            client_method="getGraphMemoryProviderSpikeOptInOperatorChecklist",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-opt-in-review-packet",
            "读取 Graph 记忆 provider spike opt-in 人工复核包",
            "getGraphMemoryProviderSpikeOptInReviewPacket",
            "GraphMemoryProviderSpikeOptInReviewPacketReport",
            client_method="getGraphMemoryProviderSpikeOptInReviewPacket",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-opt-in-decision-ledger-preview",
            "读取 Graph 记忆 provider spike opt-in 决策账本预览",
            "getGraphMemoryProviderSpikeOptInDecisionLedgerPreview",
            "GraphMemoryProviderSpikeOptInDecisionLedgerPreviewReport",
            client_method="getGraphMemoryProviderSpikeOptInDecisionLedgerPreview",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-opt-in-final-readiness-summary",
            "读取 Graph 记忆 provider spike opt-in 最终就绪摘要",
            "getGraphMemoryProviderSpikeOptInFinalReadinessSummary",
            "GraphMemoryProviderSpikeOptInFinalReadinessSummaryReport",
            client_method="getGraphMemoryProviderSpikeOptInFinalReadinessSummary",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/graph-memory-provider-spike-opt-in-human-signoff-schema-draft",
            "读取 Graph 记忆 provider spike opt-in 人工签收 schema 草案",
            "getGraphMemoryProviderSpikeOptInHumanSignoffSchemaDraft",
            "GraphMemoryProviderSpikeOptInHumanSignoffSchemaDraftReport",
            client_method="getGraphMemoryProviderSpikeOptInHumanSignoffSchemaDraft",
            status_codes=[200, 400, 404],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/retrieval-sample-export-pack",
            "读取检索失败样本导出包",
            "getRetrievalSampleExportPack",
            "RetrievalSampleExportPackReport",
            client_method="getRetrievalSampleExportPack",
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/embedding-mock-evaluation-report",
            "读取 embedding mock 对照报告",
            "getEmbeddingMockEvaluationReport",
            "EmbeddingMockEvaluationReport",
            client_method="getEmbeddingMockEvaluationReport",
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/retrieval-sample-replay-report",
            "读取检索失败样本复跑报告",
            "getRetrievalSampleReplayReport",
            "RetrievalSampleReplayReport",
            client_method="getRetrievalSampleReplayReport",
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/retrieval-sample-migration-pack",
            "读取检索失败样本迁移包",
            "getRetrievalSampleMigrationPack",
            "RetrievalSampleMigrationPackReport",
            client_method="getRetrievalSampleMigrationPack",
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/retrieval-failure-samples",
            "读取检索失败样本",
            "getRetrievalFailureSamples",
            "RetrievalFailureSamplesReport",
            client_method="getRetrievalFailureSamples",
        ),
        _endpoint(
            "stories",
            "POST",
            "/api/stories/{slug}/retrieval-failure-samples",
            "追加检索失败样本",
            "addRetrievalFailureSample",
            "RetrievalFailureSampleAppendResponse",
            client_method="addRetrievalFailureSample",
            status_codes=[200, 400, 404, 409],
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/cards-workspace",
            "读取设定卡片工作台",
            "getCardsWorkspace",
            "CardsWorkspaceReport",
            client_method="getCardsWorkspace",
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/audit-log",
            "读取项目审计日志",
            "getProjectAuditLog",
            "ProjectAuditLog",
            client_method="getProjectAuditLog",
        ),
        _endpoint(
            "stories",
            "GET",
            "/api/stories/{slug}/selected-worldline",
            "读取已选世界线",
            "getSelectedWorldline",
            "WorldlineSelectionResponse",
            client_method="getSelectedWorldline",
        ),
        _endpoint(
            "runs",
            "GET",
            "/api/tree",
            "读取世界线树",
            "getTree",
            "RunTreeResponse",
            client_method="getTree",
            status_codes=[200],
        ),
        _endpoint(
            "runs",
            "GET",
            "/api/runs",
            "读取运行列表",
            "listRuns",
            "RunListResponse",
            status_codes=[200],
        ),
        _endpoint(
            "runs",
            "GET",
            "/api/runs/{run_id}",
            "读取运行详情",
            "getRun",
            "RunDetail",
            client_method="getRun",
        ),
        _endpoint(
            "runs",
            "GET",
            "/api/runs/{run_id}/branches/{branch_id}",
            "读取分支详情",
            "getBranch",
            "BranchDetail",
            client_method="getBranch",
        ),
        _endpoint(
            "runs",
            "GET",
            "/api/runs/{run_id}/branches/{branch_id}/projection-health",
            "读取投影健康",
            "getProjectionHealth",
            "ProjectionHealthReport",
            client_method="getProjectionHealth",
        ),
        _endpoint(
            "runs",
            "GET",
            "/api/runs/{run_id}/branches/{branch_id}/reader-panel",
            "读取读者评审",
            "getReaderPanel",
            "ReaderPanelReport",
            client_method="getReaderPanel",
        ),
        _endpoint(
            "runs",
            "GET",
            "/api/runs/{run_id}/branches/{branch_id}/prompt-budget-pack",
            "读取上下文预算包",
            "getPromptBudgetPack",
            "PromptBudgetPackReport",
            client_method="getPromptBudgetPack",
        ),
        _endpoint(
            "exports",
            "GET",
            "/api/runs/{run_id}/branches/{branch_id}/chapter-export",
            "读取单章导出",
            "getChapterExport",
            "ChapterExport",
            client_method="getChapterExport",
        ),
        _endpoint(
            "exports",
            "GET",
            "/api/runs/{run_id}/branches/{branch_id}/chapter-collection-export",
            "读取章节合集导出",
            "getChapterCollectionExport",
            "ChapterCollectionExport",
            client_method="getChapterCollectionExport",
        ),
        _endpoint(
            "jobs",
            "POST",
            "/api/jobs/intervention",
            "提交干预生成任务",
            "postJobIntervention",
            "JobSubmitResponse",
            client_method="postJobIntervention",
            status_codes=[200, 400, 404, 409],
        ),
        _endpoint(
            "jobs",
            "POST",
            "/api/jobs/resume-continue",
            "提交续写任务",
            "postJobResumeContinue",
            "JobSubmitResponse",
            client_method="postJobResumeContinue",
            status_codes=[200, 400, 404, 409],
        ),
        _endpoint(
            "jobs",
            "GET",
            "/api/jobs/{job_id}",
            "读取异步任务状态",
            "getJob",
            "JobRecord",
            client_method="getJob",
        ),
        _endpoint(
            "settings",
            "GET",
            "/api/settings/runtime",
            "读取本地运行设置",
            "getRuntimeSettings",
            "RuntimeSettings",
            client_method="getRuntimeSettings",
            status_codes=[200],
        ),
        _endpoint(
            "settings",
            "GET",
            "/api/settings/model-configuration",
            "读取模型配置状态",
            "getModelConfiguration",
            "ModelConfigurationSummary",
            client_method="getModelConfiguration",
            status_codes=[200],
        ),
        _endpoint(
            "settings",
            "GET",
            "/api/settings/llm-profile-assignment",
            "读取任务模型画像",
            "getLLMProfileAssignment",
            "LLMProfileAssignmentReport",
            client_method="getLLMProfileAssignment",
            status_codes=[200],
        ),
        _endpoint(
            "settings",
            "GET",
            "/api/settings/api-contract",
            "读取本地 API 契约",
            "getApiContract",
            "ApiContractReport",
            client_method="getApiContract",
            status_codes=[200],
        ),
        _endpoint(
            "settings",
            "GET",
            "/api/settings/retrieval-samples-index",
            "读取跨项目检索样本索引",
            "getRetrievalSamplesIndex",
            "CrossProjectRetrievalSamplesIndexReport",
            client_method="getRetrievalSamplesIndex",
            status_codes=[200],
        ),
        _endpoint(
            "settings",
            "GET",
            "/api/settings/retrieval-samples-trend-snapshot",
            "读取检索样本趋势快照",
            "getRetrievalSamplesTrendSnapshot",
            "RetrievalSamplesTrendSnapshotReport",
            client_method="getRetrievalSamplesTrendSnapshot",
            status_codes=[200],
        ),
        _endpoint(
            "settings",
            "GET",
            "/api/settings/packaging-readiness",
            "读取发行准备清单",
            "getPackagingReadiness",
            "BundledReleaseReadinessReport",
            client_method="getPackagingReadiness",
            status_codes=[200],
        ),
        _endpoint(
            "settings",
            "GET",
            "/api/settings/providers",
            "读取 provider 路由状态",
            "getProviderGateway",
            "ProviderGatewaySummary",
            client_method="getProviderGateway",
            status_codes=[200],
        ),
        _endpoint(
            "settings",
            "GET",
            "/api/settings/provider-usage",
            "读取 provider usage 汇总",
            "getProviderUsage",
            "ProviderUsageSummary",
            client_method="getProviderUsage",
            status_codes=[200, 400],
        ),
        _endpoint(
            "settings",
            "GET",
            "/api/settings/local-smoke-checklist",
            "读取本地冒烟清单",
            "getLocalSmokeChecklist",
            "LocalSmokeChecklist",
            client_method="getLocalSmokeChecklist",
            status_codes=[200],
        ),
        _endpoint(
            "settings",
            "GET",
            "/api/settings/release-preflight",
            "读取发布前检查",
            "getReleasePreflight",
            "ReleasePreflightChecklist",
            client_method="getReleasePreflight",
            status_codes=[200],
        ),
        _endpoint(
            "settings",
            "GET",
            "/api/settings/commercial-status-overview",
            "读取商业化状态总览",
            "getCommercialStatusOverview",
            "CommercialStatusOverview",
            client_method="getCommercialStatusOverview",
            status_codes=[200],
        ),
    ]
